### ISSUE TITLE
Feature request - customizing location at runtime

### ISSUE THREAD

**Issue by bufke** [jschneier/django-storages-redux#16]
I'd be open to paying someone for this. In django-storages (the original project on pypi) I can extend S3BotoStorage like this

```
class MediaRootS3BotoStorage(S3BotoStorage):
    def __init__(self, *args, **kwargs):
        path = 'media'
        if hasattr(connection, 'schema_name'):
            path = path + '/' + connection.schema_name
        kwargs['location'] = path
        super(MediaRootS3BotoStorage, self).__init__(*args, **kwargs)
```

This let's me save media in different folders when using django-tenant-schemas. It might look like `/media/tenant1` and `/media/tenant2`. With redux however the location seems to just always be whatever first tenant I use. I'd like to use django-storages-redux over the original for the many bug fixes, particularly the timezone and S3 stuff.

**Comment by bufke** [comment]
Actually I found a way to extend it without editing django-storages itself using a property and setter. 

```
class MediaRootS3BotoStorage(S3BotoStorage):                                     
    @property                                                                    
    def location(self):                                                          
        path = 'media'                                                           
        if hasattr(connection, 'schema_name'):                                   
            path = path + '/' + connection.schema_name                           
        return path                                                              
                                                                                 
    @location.setter                                                             
    def location(self, value):                                                   
        pass
```

Closing the issue - if you think this would be a useful feature for django-storages I'd be happy to submit a get_location function that would be a less hacky way to do it.

**Comment by jschneier** [comment]
Sorry I didn't respond to this earlier. A couple things:

* I haven't meaningfully changed any of the logic around the settings things due to not wanting to break backwards compat. In fact, if you look [here](https://github.com/jschneier/django-storages-redux/blob/master/storages/backends/s3boto.py#L251-L254) it seems like location should be overridable via ``__init__`` just fine
* I looked at the old tickets/PR/discussions about the various timezone issues and it doesn't look like anyone came to any real conclusion either way and/or they were waiting on more "official" word from django  so I'm not entirely sure if the timezone fixes you mention are in this code base

Thanks for the interest in the fork!
